package com.soma.lof.match.repository

import com.soma.lof.match.model.dto.FakeMatchDataResponse
import com.soma.lof.match.model.entity.DateInfo
import com.soma.lof.match.model.entity.MatchData
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.flow
import java.util.*

class FakeMatchRepositoryImpl() : FakeMatchRepository {

    val data = FakeMatchDataResponse("8월",
        listOf(
            DateInfo("1일", "#000000"),
            DateInfo("2일", "#426BFF"),
            DateInfo("3일", "#E2012D"),
            DateInfo("4일", "#000000"),
            DateInfo("5일", "#000000"),
            DateInfo("6일", "#000000"),
            DateInfo("7일", "#000000"),
            DateInfo("8일", "#000000"),
            DateInfo("9일", "#426BFF"),
            DateInfo("10일", "#E2012D"),
            DateInfo("11일", "#000000"),
            DateInfo("12일", "#000000"),
            DateInfo("13일", "#000000"),
            DateInfo("14일", "#000000"),
        ),
        listOf(
            listOf(
                MatchData(
                    1L,
                    "DK",
                    "https://cdn.pixabay.com/photo/2018/05/13/16/57/dog-3397110__480.jpg",
                    "T1",
                    "https://cdn.pixabay.com/photo/2018/05/13/16/57/dog-3397110__480.jpg",
                    "17:00",
                    "LCK",
                    false,
                    0,
                    0,
                    isHide = true,
                    isFinish = true),
                MatchData(
                    2L,
                    "DK",
                    "https://cdn.pixabay.com/photo/2018/05/13/16/57/dog-3397110__480.jpg",
                    "T1",
                    "https://cdn.pixabay.com/photo/2018/05/13/16/57/dog-3397110__480.jpg",
                    "17:00",
                    "LCK",
                    false,
                    0,
                    0,
                    isHide = true,
                    isFinish = true),
                MatchData(
                    3L,
                    "DK",
                    "https://cdn.pixabay.com/photo/2018/05/13/16/57/dog-3397110__480.jpg",
                    "T1",
                    "https://cdn.pixabay.com/photo/2018/05/13/16/57/dog-3397110__480.jpg",
                    "17:00",
                    "LCK",
                    false,
                    0,
                    0,
                    isHide = true,
                    isFinish = true),
                MatchData(
                    4L,
                    "DK",
                    "https://cdn.pixabay.com/photo/2018/05/13/16/57/dog-3397110__480.jpg",
                    "T1",
                    "https://cdn.pixabay.com/photo/2018/05/13/16/57/dog-3397110__480.jpg",
                    "17:00",
                    "LCK",
                    false,
                    0,
                    0,
                    isHide = true,
                    isFinish = true)
            ),
            listOf(
                MatchData(
                    4L,
                    "DK",
                    "https://cdn.pixabay.com/photo/2018/05/13/16/57/dog-3397110__480.jpg",
                    "T1",
                    "https://cdn.pixabay.com/photo/2018/05/13/16/57/dog-3397110__480.jpg",
                    "17:00",
                    "LCK",
                    false,
                    0,
                    0,
                    isHide = true,
                    isFinish = true),
                MatchData(
                    5L,
                    "DK",
                    "https://cdn.pixabay.com/photo/2018/05/13/16/57/dog-3397110__480.jpg",
                    "T1",
                    "https://cdn.pixabay.com/photo/2018/05/13/16/57/dog-3397110__480.jpg",
                    "17:00",
                    "LCK",
                    false,
                    0,
                    0,
                    isHide = true,
                    isFinish = true),
                MatchData(
                    6L,
                    "DK",
                    "https://cdn.pixabay.com/photo/2018/05/13/16/57/dog-3397110__480.jpg",
                    "T1",
                    "https://cdn.pixabay.com/photo/2018/05/13/16/57/dog-3397110__480.jpg",
                    "17:00",
                    "LCK",
                    false,
                    0,
                    0,
                    isHide = true,
                    isFinish = true),
                MatchData(
                    7L,
                    "DK",
                    "https://cdn.pixabay.com/photo/2018/05/13/16/57/dog-3397110__480.jpg",
                    "T1",
                    "https://cdn.pixabay.com/photo/2018/05/13/16/57/dog-3397110__480.jpg",
                    "17:00",
                    "LCK",
                    false,
                    0,
                    0,
                    isHide = true,
                    isFinish = true)
            ),
            listOf(
                MatchData(
                    8L,
                    "DK",
                    "https://cdn.pixabay.com/photo/2018/05/13/16/57/dog-3397110__480.jpg",
                    "T1",
                    "https://cdn.pixabay.com/photo/2018/05/13/16/57/dog-3397110__480.jpg",
                    "17:00",
                    "LCK",
                    false,
                    0,
                    0,
                    isHide = true,
                    isFinish = true),
                MatchData(
                    9L,
                    "DK",
                    "https://cdn.pixabay.com/photo/2018/05/13/16/57/dog-3397110__480.jpg",
                    "T1",
                    "https://cdn.pixabay.com/photo/2018/05/13/16/57/dog-3397110__480.jpg",
                    "17:00",
                    "LCK",
                    false,
                    0,
                    0,
                    isHide = true,
                    isFinish = true),
                MatchData(
                    10L,
                    "DK",
                    "https://cdn.pixabay.com/photo/2018/05/13/16/57/dog-3397110__480.jpg",
                    "T1",
                    "https://cdn.pixabay.com/photo/2018/05/13/16/57/dog-3397110__480.jpg",
                    "17:00",
                    "LCK",
                    false,
                    0,
                    0,
                    isHide = true,
                    isFinish = true),
                MatchData(
                    11L,
                    "DK",
                    "https://cdn.pixabay.com/photo/2018/05/13/16/57/dog-3397110__480.jpg",
                    "T1",
                    "https://cdn.pixabay.com/photo/2018/05/13/16/57/dog-3397110__480.jpg",
                    "17:00",
                    "LCK",
                    false,
                    0,
                    0,
                    isHide = true,
                    isFinish = true)
            ),
            listOf(),
            listOf(),
            listOf(),
            listOf(),
            listOf(),
            listOf(),
            listOf(),
            listOf(),
            listOf(),
            listOf(),
            listOf(),
        )
    )

    override fun getMatchData(): Flow<FakeMatchDataResponse> =

        flow {
            emit(data)
        }

}