object Versions {
    const val gradlePlugin = "7.2.2"
    const val kotlin = "1.6.10"
    const val hilt = "2.42"
    const val coroutineCore = "1.6.1"
    const val coroutineAndroid = "1.6.1"
    const val gson = "2.8.6"
    const val retrofit = "2.9.0"
    const val glide = "4.13.2"
    const val navigation = "2.5.0"
    const val lifecycle = "2.5.0"
    const val lifecycleRuntime = "2.4.0-alpha02"
    const val eventBus = "3.2.0"
    const val mpAndroidChart = "v3.1.0"
    const val paging = "3.1.1"
    const val okHttp = "3.12.1"
    const val googleService = "4.3.10"
}